### ISSUE TITLE
signal.NotifyContext() instead of importing a 3rd party module

### ISSUE THREAD

**Issue by alexballas** [DictumMortuum/database-exporter#1]
https://github.com/DictumMortuum/database-exporter/blob/e2b73a3de7ba1c62d815892557e0c16c13eac386/main.go#L47
You could replace the highlighted line with
```go
ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
defer stop()
```
and avoid importing a 3rd party module

**Comment by DictumMortuum** [comment]
Nice :D
